[package]
name = "citeproc"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
ducc = "0.1.0"
html2md = "0.2.9"
once_cell = "0.2.2"
